# Generated by Django 3.0.7 on 2020-07-13 09:46

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0002_remove_userfile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='filename'),
        ),
    ]
