# Generated by Django 3.0.7 on 2020-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0003_userfile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
