# Generated by Django 3.0.7 on 2020-07-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0005_auto_20200713_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='countdown',
            field=models.DateTimeField(null=True),
        ),
    ]
